"""
ZMUX CLI — transparent Unix shell integration.

The executable wrappers generated by :func:`zmux.paths.ensure_cli_wrappers`
re-enter the Python runtime through this module::

    python -m zmux.cli <cmd> [args...]

Each wrapper forwards ``"$0"`` (its own invoked path) as the first argument,
so the typed command name is recovered with ``os.path.basename(argv[0])``.
This is what makes ZMUX built-in commands (``zpip``, ``help``, ``zmux-info``,
``clear``, ``pip``) work natively inside the real Android PTY shell
(``/system/bin/sh``) instead of failing with "inaccessible or not found".
"""
from __future__ import annotations

import os
import shlex
import subprocess
import sys

#: Commands handled by this module (mirrors zmux.paths.CLI_COMMANDS).
COMMANDS = ("zpip", "help", "zmux-info", "clear", "pip")

_USAGE = "usage: python -m zmux.cli <zpip|help|zmux-info|clear|pip> [args...]"

_PIP_FALLBACK = """pip is not available inside this ZMUX runtime.
Use the ZMUX package manager instead:
  zpip search <name>      Search for packages
  zpip info <name>        Show package info
  zpip install <name>     Install a package
  zpip list               List installed packages
  zpip verify <name>      Verify a package installation
  zpip uninstall <name>   Uninstall a package
  zpip doctor             Check system health"""


def _cmd_help() -> int:
    """Print the formatted ZMUX terminal help text."""
    from zmux.terminal import HELP_TEXT
    sys.stdout.write(HELP_TEXT)
    if not HELP_TEXT.endswith("\n"):
        sys.stdout.write("\n")
    return 0


def _cmd_clear() -> int:
    """Clear the terminal: home cursor, clear screen and scrollback buffer."""
    sys.stdout.write("\033[H\033[2J\033[3J")
    return 0


def _cmd_zmux_info() -> int:
    """Print the formatted ZMUX runtime fingerprint."""
    from zmux import zpip
    print(zpip.format_fingerprint(zpip.runtime_fingerprint()))
    return 0


def _cmd_zpip(args: list) -> int:
    """Run a zpip command and print terminal-friendly formatted output."""
    from zmux import zpip
    command = "zpip" + (" " + shlex.join(args) if args else "")
    output, exit_code = zpip.format_output(command, zpip.dispatch(command))
    print(output)
    return exit_code


def _cmd_pip(args: list) -> int:
    """Run standard pip, or explain how to use zpip when pip cannot run.

    On Android, Python lives inside the app as a shared library, so
    ``sys.executable`` is often not a runnable standalone interpreter;
    the ZABAWHEELS-native ``zpip`` package manager is the supported path.
    """
    executable = sys.executable or ""
    if executable and os.access(executable, os.X_OK):
        try:
            return subprocess.call([executable, "-m", "pip", *args])
        except OSError:
            pass
    print(_PIP_FALLBACK)
    return 1


def main(argv=None) -> int:
    """CLI entrypoint. Returns the process exit code."""
    argv = list(sys.argv[1:] if argv is None else argv)
    if not argv:
        print(_USAGE, file=sys.stderr)
        return 2
    command = os.path.basename(argv[0])
    args = argv[1:]
    if command == "help":
        return _cmd_help()
    if command == "clear":
        return _cmd_clear()
    if command == "zmux-info":
        return _cmd_zmux_info()
    if command == "zpip":
        return _cmd_zpip(args)
    if command == "pip":
        return _cmd_pip(args)
    print(f"zmux.cli: unknown command: {command}", file=sys.stderr)
    print(_USAGE, file=sys.stderr)
    return 127


if __name__ == "__main__":
    sys.exit(main())
