"""
ZMUX Path Resolution & Directory Management

Handles APP_DIR detection for Android and Desktop environments.
All runtime directories are app-private and gitignored.
"""

import os
import shlex
import stat
from pathlib import Path


def _is_writable(path: Path) -> bool:
    """Check if a directory can be created and written to."""
    try:
        path.mkdir(parents=True, exist_ok=True)
        test_file = path / ".zmux_write_test"
        test_file.write_text("ok", encoding="utf-8")
        test_file.unlink(missing_ok=True)
        return True
    except OSError:
        return False


def resolve_app_dir() -> Path:
    """
    Resolve the application directory based on runtime environment.
    
    Priority:
    1. ANDROID_PRIVATE / ANDROID_ARGUMENT / ANDROID_APP_PATH env vars (p4a webview bootstrap)
    2. Fallback: project root (where main.py lives) for desktop development
    3. Safe Android / POSIX writable fallbacks
    """
    for env_key in ("ANDROID_PRIVATE", "ANDROID_ARGUMENT", "ANDROID_APP_PATH"):
        val = os.environ.get(env_key)
        if val:
            candidate = Path(val)
            if _is_writable(candidate):
                return candidate

    default_root = Path(__file__).resolve().parent.parent
    if _is_writable(default_root):
        return default_root

    for candidate_str in (
        os.environ.get("HOME", ""),
        os.environ.get("TMPDIR", ""),
        "/data/local/tmp/zmux",
        "/cache/zmux",
        "/tmp/zmux",
    ):
        if candidate_str:
            candidate = Path(candidate_str)
            if _is_writable(candidate):
                return candidate

    return default_root


APP_DIR = resolve_app_dir()

# Critical directories - all app-private
HOME_DIR = APP_DIR / "home"
PROJECTS_DIR = HOME_DIR / "projects"
CACHE_DIR = APP_DIR / "cache"
DOWNLOADS_DIR = CACHE_DIR / "downloads"
STAGING_DIR = APP_DIR / "staging"
USER_PACKAGES_DIR = APP_DIR / "user_packages"
INSTALLED_DIR = APP_DIR / "installed"
LOG_DIR = APP_DIR / "logs"
BIN_DIR = APP_DIR / "bin"

# Ensure all directories exist with restricted permissions (owner-only).
# On Android this keeps app-private data inaccessible to other apps and
# prevents accidental exposure via shared storage providers.
for directory in [
    HOME_DIR,
    PROJECTS_DIR,
    CACHE_DIR,
    DOWNLOADS_DIR,
    STAGING_DIR,
    USER_PACKAGES_DIR,
    INSTALLED_DIR,
    LOG_DIR,
    BIN_DIR,
]:
    directory.mkdir(parents=True, exist_ok=True)
    try:
        os.chmod(directory, stat.S_IRWXU)  # 0o700
    except OSError:
        pass


# ---------------------------------------------------------------------------
# Transparent Unix shell integration
#
# The real Android PTY shell (/system/bin/sh) can only execute binaries and
# scripts that live on $PATH — typing "zpip", "help", "zmux-info", "clear" or
# "pip" otherwise fails with "/system/bin/sh: <cmd>: inaccessible or not found".
# ZMUX therefore auto-generates tiny executable wrappers inside BIN_DIR so the
# commands resolve natively in any /system/bin/sh session.
# ---------------------------------------------------------------------------

#: Commands that get an executable shell wrapper inside BIN_DIR.
CLI_COMMANDS = ("zpip", "help", "zmux-info", "clear", "pip")

#: Wrapper template shared by every ZMUX command. Each script re-enters the
#: Python runtime via ``python -m zmux.cli "$0" "$@"`` so the typed command
#: name is recovered from the invoked path. ``PYTHONPATH`` is pinned to the
#: directory that contains the ``zmux`` package because child shells spawned
#: by app-private processes do not necessarily inherit it.
_CLI_WRAPPER_TEMPLATE = """#!/system/bin/sh
# ZMUX CLI wrapper — auto-generated by zmux.paths.ensure_cli_wrappers().
# Do not edit manually; this file is rewritten on every app start.
export PYTHONPATH={app_dir}"${{PYTHONPATH:+:$PYTHONPATH}}"
if command -v python >/dev/null 2>&1; then
    exec python -m zmux.cli "$0" "$@"
fi
if command -v python3 >/dev/null 2>&1; then
    exec python3 -m zmux.cli "$0" "$@"
fi
echo "zmux: Python runtime not found on PATH" >&2
exit 127
"""


def _prepend_to_path(directory: Path) -> None:
    """Prepend a directory to os.environ["PATH"] (idempotent)."""
    entry = str(directory)
    current = os.environ.get("PATH", "")
    parts = current.split(os.pathsep) if current else []
    if entry not in parts:
        os.environ["PATH"] = entry + (os.pathsep + current if current else "")


def ensure_cli_wrappers() -> Path:
    """
    (Re)generate the executable ZMUX shell wrappers inside BIN_DIR.

    Every wrapper is a ``#!/system/bin/sh`` script that execs
    ``python -m zmux.cli "$0" "$@"`` (falling back to ``python3`` when
    ``python`` is unavailable) and is chmod'ed 0o755. BIN_DIR is also
    prepended to ``os.environ["PATH"]`` so the current process and all of
    its children resolve the commands transparently.
    """
    BIN_DIR.mkdir(parents=True, exist_ok=True)
    # Directory that contains the "zmux" package (importable via -m).
    package_root = Path(__file__).resolve().parent.parent
    content = _CLI_WRAPPER_TEMPLATE.format(app_dir=shlex.quote(str(package_root)))
    for name in CLI_COMMANDS:
        wrapper = BIN_DIR / name
        try:
            current = wrapper.read_text(encoding="utf-8") if wrapper.exists() else None
        except OSError:
            current = None
        if current != content:
            wrapper.write_text(content, encoding="utf-8", newline="\n")
        os.chmod(wrapper, 0o755)
    _prepend_to_path(BIN_DIR)
    return BIN_DIR


# Generate the wrappers and expose BIN_DIR on PATH at import time so the
# commands work from the very first PTY session. Never let a filesystem hiccup
# break app startup — the worst case is the legacy "not found" behaviour.
try:
    ensure_cli_wrappers()
except OSError:
    pass
